### ISSUE TITLE
Add tensorflow cheat sheet

### ISSUE THREAD

**Issue by cpury** [kailashahirwar/cheatsheets-ai#1]
You're missing the obvious one, that's even in your tags! :)

The closest to one I found, but it's not open source: https://www.altoros.com/tensorflow-cheat-sheet.html

Maybe we can build one as a community, start as a markdown file that anyone can edit via PR, and then at some point translate it to a poster.

**Comment by kailashahirwar** [comment]
Thanks @cpury . Good suggestion. I just added the pdf version of Altoros Tensorflow cheat sheet. I am also working on a Tensorflow cheat sheet at Mate Labs. Will share it with you all soon.
