### ISSUE TITLE
The words is so small .not suit for printing

### ISSUE THREAD

**Issue by zhangxu999** [kailashahirwar/cheatsheets-ai#2]
those documents was very good ,but 
the words on the pdf or jpg are very smal .When I have  print  this documents ,I can't see it barely.
could you provide some doc that suit for printing?
thanks

**Comment by kailashahirwar** [comment]
I am working on that. I will upload cheat sheets in printable formats soon. Till then use pdf and png/jpg versions.

**Comment by zhangxu999** [comment]
Thanks ~~
