### ISSUE TITLE
Neural Network Zoo Prequel

### ISSUE THREAD

**Issue by set92** [kailashahirwar/cheatsheets-ai#4]
I found this one that maybe is a good addition to the list.
http://www.asimovinstitute.org/neural-network-zoo-prequel-cells-layers/

And I think at least for the NN Zoo it would be great having the source http://www.asimovinstitute.org/neural-network-zoo/ because it has much more information and explanation. Although I found the post in 1 second, but well, easier to access.

**Comment by kailashahirwar** [comment]
Added. Thanks for the suggestion.
