### ISSUE TITLE
Medium link is broken/unavailable

### ISSUE THREAD

**Issue by siddesh001** [kailashahirwar/cheatsheets-ai#86]
The medium link u have appended at the end of README.md does not work. Pls look into fixing it.

**Comment by qwertpi** [comment]
It works for me, I wonder if your browser is struggling with the redirect to https://startupsventurecapital.com/essential-cheat-sheets-for-machine-learning-and-deep-learning-researchers-efb6a8ebd2e5 for some reason

**Comment by kailashahirwar** [comment]
@qwertpi Thanks. @siddesh001 It works for me as well. Check again and let me know.
