### ISSUE TITLE
What tools are used to make it？

### ISSUE THREAD

**Issue by husthuke** [kailashahirwar/cheatsheets-ai#89]
What tools are used to make it？such as numpy etc，thx

**Comment by nlpjoe** [comment]
It's an important question. Tell us so we can make a contribution. It's so old, many things need to be updated like pytorch etc. @kailashahirwar

**Comment by BrianChanCN** [comment]
Please tell us the name of tools and commit the source files that we can edit it. Thanks!

**Comment by kailashahirwar** [comment]
@BrianChanCN @nlpjoe Most of the cheatsheets can be re-created using Microsoft word.

**Comment by kailashahirwar** [comment]
@husthuke You can use Microsoft Word or Photoshop to create these cheatsheets.
